version: '3'
services:
  app:
    container_name: formation-nodejs-app
    image: node:8.4.0
    user: node
    entrypoint: npm
    command: start
    working_dir: /workspace
    volumes:
      - .:/workspace
    ports:
      - 3000:3000
    depends_on:
      - redis
  redis:
    container_name: formation-nodejs-redis
    image: redis:4.0.1
